### PR TITLE
api: del x[123]

### LINKED ISSUE #40: Cannot subclass?
Hi:
I am trying to create a simple subclass of `intbitset` without luck:
```
>>> from intbitset import intbitset
>>> class MySet(intbitset):
...  def __init__(a1, a2):
...   super(MySet, self).__init__(range(a1, a2))
... 
>>> MySet(1, 10)
Exception TypeError: '__del__() takes exactly one argument (0 given)' in <built-in method __del__ of MySet object at 0x7f21724b9158> ignored
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes exactly 2 arguments (3 given)

>>> class MySet(intbitset):
...  def __new__(cls, *args):
...   return intbitset.__new__(cls, args)
... 
>>> MySet([1, 10])
intbitset([1])
>>> MySet(1, 10)
Exception TypeError: '__del__() takes exactly one argument (0 given)' in <built-in method __del__ of MySet object at 0x7f21724b9260> ignored
intbitset([1, 10])

```

and then in the same session as above:
```
>>> a=intbitset([1,2,5])
>>> a=intbitset([1,2,5,1000])
>>> a=intbitset([1,2,5])
>>> b=intbitset([1,2,5,1000])
>>> d={a: 12}
>>> d
Exception TypeError: '__del__() takes exactly one argument (0 given)' in <built-in method __del__ of MySet object at 0x7f21724b92b8> ignored
{intbitset([1, 2, 5]): 12}
```

### PR DESCRIPTION
**Pull request by kaplun**
* FIX Fixes implementation of del x[123] operator which was wrongly
  defined as __del__ rathern than __delitem__.
  (Closes #40)

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>
Reported-by: Philippe Ombredanne <pombredanne@gmail.com>

### CODE REVIEW

**Comment by jirikuncar** [comment]
LGTM `s/(Closes #40)/(closes #40)/`

**Comment by kaplun** [comment]
Did you mean like this?

**Comment by jirikuncar** [comment]
@kaplun can you rebase too?

**Comment by kaplun** [comment]
Right! See: #45

**Pull request merged**
