### PR TITLE
intbitset v2.3.0

### PR DESCRIPTION
**Pull request by kaplun**
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
@tiborsimko @jirikuncar

**Comment by kaplun** [comment]
I am bumping middle release due to the change in license (albeit non technically breaking in case of upgrade it is still notable and worthing more than a patch release).

**Comment by jirikuncar** [comment]
Why not `v2.2.2`? There are only bugfixes in this release.

**Comment by kaplun** [comment]
> Why not v2.2.2? There are only bugfixes in this release.

I explained right above:
> I am bumping middle release due to the change in license (albeit non technically breaking in case of upgrade it is still notable and worthing more than a patch release).

The license change is not so minor of a change for an Open source software.

**Comment by jirikuncar** [comment]
> I explained it right above:

Timing issue :)

**Comment by jirikuncar** [comment]
@kaplun `git commit --amend -m 'release: v2.3.0' -s` (+rebase)

**Comment by kaplun** [comment]
:ship:

**Pull request merged**
