### PR TITLE
Test also on Python 3.5 and 3.6

### PR DESCRIPTION
**Pull request by pombredanne**
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by pombredanne** [comment]
@kaplun New commit added and all tests pass too on Python 3.5 and 3.6

Do you really want to disable the testing with tox and Travis for py25, py26, py33, py34 ?

**Comment by pombredanne** [comment]
Note that I am fine with this on my side: I care only for 2.7, 3.5 and 3.6.

**Comment by pombredanne** [comment]
@kaplun Let push the removal of older pythons and you can pick or ignore these changes as you please.

**Comment by kaplun** [comment]
Yeah, actually since you are fine with Python 2.7, I think it's better to reduce the testing matrix to ease Travis load. AFAIK `intbitset` independent library (beside your project) had been used only by Invenio 2.x which is anyway deprecated, so I believe we can nicely upgrade the requirements.

**Comment by pombredanne** [comment]
@kaplun beside all users of invenio and invenio forks (https://github.com/search?l=Python&q=intbitset&type=Code) these are a few other users:
- https://github.com/aeonium/lw-daap/blob/d6423f2941df8433e7167e56ac9dccd1c65d1a0a/requirements.txt#L20
- https://github.com/athoune/InverseDB/blob/40d08bd5757f847534ea1f25721ad91f807773ae/setup.py#L33
- https://github.com/3D-e-Chem/kripodb/blob/21eaa894ff59d8a4126a317c6f0f7acade059d92/setup.py#L13

But I guess this will not be an issue from drop older pythons support there

**Comment by pombredanne** [comment]
In any case I also fixed the `setup.py` classifiers accordingly.

**Comment by pombredanne** [comment]
@kaplun Thanks for the merge squashing! I could have done the squashing alright too.

**Comment by kaplun** [comment]
:+1: didn't dare ask further :dancer:

**Pull request closed without merging**
