### PR TITLE
Comparison with other types

### LINKED ISSUE #18: Support comparisons with other types.
Using any comparison operator on an intbiset with anything that is not an intbitset results in the following:

``` python
TypeError: Argument 'rhs' has incorrect type (expected intbitset.intbitset, got something_else)
```

It should instead return `False` as a `set` would.

### PR DESCRIPTION
**Pull request by kaplun**
- Comparing an intbitset with anything that is not an intbitset
  should behave as a set would. E.g.
  intbitset([1,2,3]) == set([1,2,3]) is False.
  (closes #18)

Signed-off-by: Samuele Kaplun samuele.kaplun@cern.ch
Reported-by: Dimitrios Semitsoglou-Tsiapos dsemitso@cern.ch

### CODE REVIEW

**Comment by jirikuncar** [comment]
@kaplun since the commit messages are not following the *inveniosoftware* standards, I can't use the automatic release notes generator, hence it will take more time.

**Comment by pombredanne** [comment]
I will be reviewing and may be rebasing and merging this at last!

**Comment by dset0x** [comment]
Four years sure fly by quickly.

**Comment by lnielsen** [comment]
Closing PR as it's stale for several years.

**Comment by pombredanne** [comment]
Actually this is not readility mergeable... my bad. Closing indeed.

**Comment by dset0x** [comment]
I was really counting on this one. (´д｀)

**Comment by lnielsen** [comment]
Just FYI, I was doing cleanup of old pull requests in inveniosoftware organisation, that was the main reason to close it since it was open since 2014 :-)

**Comment by pombredanne** [comment]
@dset0x we can implement it still... but the code in this PR was stale and not exactly working as expected.

**Pull request closed without merging**
