### PR TITLE
#43 Refine README

### PR DESCRIPTION
**Pull request by pombredanne**
Explain that the set is a sorted set and highlight some its sequence-like features.

### CODE REVIEW

**Comment by kaplun** [comment]
@pombredanne just to make your contribution perfect, can you amend the commit logs to respect the inveniosoftware conventions:

http://invenio.readthedocs.io/en/latest/technology/git.html#r2-remarks-on-commit-log-messages

**Comment by pombredanne** [comment]
@kaplun there you go. Practice makes perfect.

**Comment by kaplun** [comment]
Almost :smile: 

```
README: enhanced documentation 
 * Explains that intbitset is a sorted set.
 * Highlights some intbitset sequence-like features.
 * Explains the integer range supported by intbitset.
   (closes #43)
Signed-off-by: Philippe Ombredanne <pombredanne@gmail.com>
```

**Comment by jirikuncar** [comment]
@kaplun almost (see `kwalitee check message`) - there should be an empty line after each bullet point.

**Comment by pombredanne** [comment]
@kaplun @jirikuncar Commit amended

**Pull request merged**
