### PR TITLE
Rename version.py to intbitset_version.py

### PR DESCRIPTION
**Pull request by maxyz**
This is to avoid polluting the namespace

### CODE REVIEW

**Comment by lnielsen** [comment]
Thanks for the PR. Can you explain a bit more in detail what the problem with ``version.py`` vs. ``intuit_version.py``? We have ``version.py`` in all our packages on https://github.com/inveniosoftware/, hence we prefer to keep them all the same way unless there's good reasons for not to.

**Comment by maxyz** [comment]
¡Hola Lars!

El 2017-08-11 a las 07:46 -0700, Lars Holm Nielsen escribió:
> Thanks for the PR. Can you explain a bit more in detail what the problem with 
> version.py vs. intuit_version.py? We have version.py in all our packages on 
> https://github.com/inveniosoftware/, hence we prefer to keep them all the same 
> way unless there's good reasons for not to.

I'll give it a try.

Currently the version.py is installed by the setup.py in a way that if you
launch an interpreter and run:
 import version
the module being loaded is the one being shipped in the intbitset that sets 
__version__ to the intbitset version.

This is unacceptable for a distribution package such as Debian. Thus the 
module rename.

Happy hacking,
-- 
"Nothing ever goes away." -- Commoner's Law of Ecology
 Saludos /\/\ /\ >< `/

**Comment by greut** [comment]
what about adding a `__init__.py` into the same folder?

**Comment by pombredanne** [comment]
@greut Wrapping everything nicely under an intbitset dir with its `__init__.py` would be fine.
e.g. you would end up with something deployed like:
``
intbitset/
intbitset/__init__.py
intbitset/version.py
intbitset/helper.py
```

Note that the issue is not only for Debian but quite general and a source of possible errors.

**Comment by pombredanne** [comment]
@greut if all your invenio packages deploy a top level `version.py` then every package overwrites the other I guess when they are installed together. So this cannot work out sanely even for you.

**Comment by lnielsen** [comment]
Got it, thanks a lot the explanation. I agree with @greut it's rather a ``__init__.py`` missing under a package directory (which is also the case for all our other packages).

**Comment by lnielsen** [comment]
I don't see we will get everything moved in under a package within a reasonable timeframe, so if you'd like to submit a PR doing that would be great, otherwise I'm also happy to merge this PR.

**Comment by pombredanne** [comment]
ping?

**Comment by pombredanne** [comment]
@maxyz Thank you ++ ... FYI, I have taken over the maintenance of this library.

**Pull request merged**
